### ISSUE TITLE
Move the instructions to the main Readme

### ISSUE THREAD

**Issue by andreaTP** [redhat-developer/kiota-js-extra#3]
I think that we should include the instructions for usage in the top-level Readme file.

**Comment by EricWittmann** [comment]
The advantage of having them in the module is that they then get included in the package published to npmjs.com:

https://www.npmjs.com/package/@redhat-developer/kiota-gen

As long as they end up there as well, I don't much care.  We could just link to the module readme from the top level readme.  Or we can change the build to pull the root readme into the published npm package.

wdyt?

**Comment by EricWittmann** [comment]
Fixed in https://github.com/redhat-developer/kiota-js-extra/pull/6
