### ISSUE TITLE
Supporting KIOTA_LOCAL or something similar

### ISSUE THREAD

**Issue by sebastienlevert** [redhat-developer/kiota-js-extra#8]
Howdy!

## Challenge 

I was doing some Node tests today and I wanted to run kiota as part of my npm scripts. Great opportunity to jump on the `kiota-gen` bandwagon! 

Though, I'm working to test stuff that are available from a version not yet available (new TS generation using our Proxy patterns). So I wanted to use the local version of my kiota installation vs. something that would be downloaded from the cloud. 

## Proposal

Adding a new ENV that would automatically skip the downloads and install and just "symlink" to my local installation would be super useful. It would also be a good way to leverage the machine installed version of kiota if this is something you'd want (I'm not sure why, but maybe?).

**Comment by sebastienlevert** [comment]
I did something funky... Creating 3 kiota scripts in my `package.json`.

```json
"kiota:install": "kiota --version",
"kiota:override": "cp /home/slevert/src/microsoft/kiota/src/kiota/bin/Release/net8.0/linux-x64/publish/kiota .kiota/v1.9.1/kiota",
"kiota:generate": "kiota generate -l typescript -d https://aka.ms/graph/v1.0/openapi.yaml -e '/me/**' -e '/me' -c GraphClient -o ./src/generated",
```

So I'm hacking it, but "kinda" works as I need to sequence these calls. Would be great to identify an easier way for that!

**Comment by andreaTP** [comment]
Hi @sebastienlevert , great to see you around!

I would welcome the option to use a specific binary on the path.
As a workaround, I think that you should be able to use your local version by setting `KIOTA_VERSION` to a fixed value and `KIOTA_DOWNLOAD_DIR` to a folder matching the expected path and containing the binary.

**Comment by andreaTP** [comment]
Looking twice at the code it might be tricky, if even possible, to use the workaround.
It will probably be faster to just implement the handling of `KIOTA_LOCAL`.

**Comment by sebastienlevert** [comment]
I had the same feeling. When going through the code I wasn't able to just specify a specific binary. Either a KIOTA_LOCAL or KIOTA_BINARY that would override the rest of the automated download / install would probably be enough.

**Comment by andreaTP** [comment]
Agree, feel free to submit a PR or I'll eventually take it (on PTO today).
